import { Tag } from '@portfolio/domains/tag-canvas';

export const DEFAULT_TAGS: Tag[] = [
  { href: '#', label: 'HTML' },
  { href: '#', label: 'CSS' },
  { href: '#', label: 'TypeScript' },
  { href: '#', label: 'JavaScript' },
  { href: '#', label: 'REST' },
  { href: '#', label: 'JSON' },
  { href: '#', label: 'Angular' },
  { href: '#', label: 'Spring boot' },
  { href: '#', label: 'Node.js' },
  { href: '#', label: 'Nest.js' },
  { href: '#', label: 'Git' },
  { href: '#', label: 'GitHub' },
  { href: '#', label: 'BitBucket' },
  { href: '#', label: 'Tailwind' },
  { href: '#', label: 'SQL' },
  { href: '#', label: 'PostgreSQL' },
  { href: '#', label: 'NoSQL' },
  { href: '#', label: 'MongoDB' },
  { href: '#', label: 'Java' },
  { href: '#', label: 'React' },
  { href: '#', label: 'Redux' },
  { href: '#', label: 'ContextApi' },
  { href: '#', label: 'Next.js' },
];
